### ISSUE TITLE
yolov4 weights for airbus ship detection dataset

### ISSUE THREAD

**Issue by arjunno** [codelover96/Airbus-Ship-Detection-with-YOLOv4#1]
plz upload trained model weight

**Comment by codelover96** [comment]
Try these [weights](https://drive.google.com/file/d/186nSF5YlRBZHGFRfNwWh7E1RVTtAD9K-/view?usp=sharing)
For instructions on how to run and train please look at Youtube section of Readme.md
~codelover96
